--
-- PostgreSQL database dump  
--

-- I am providing this dump temporarily to capture what the database schema acts as
-- and as a way to implement this on your local end while the website is down for testing

-- Dumped from database version 15.3
-- Dumped by pg_dump version 15.3

-- Started on 2024-07-18 08:09:29

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3488 (class 1262 OID 16713)
-- Name: quizstudy; Type: DATABASE; Schema: -; Owner: skroskznik
--

CREATE DATABASE quizstudy WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE_PROVIDER = libc LOCALE = 'English_United States.1252';


\connect quizstudy

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 221 (class 1259 OID 16737)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- TOC entry 220 (class 1259 OID 16736)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 223 (class 1259 OID 16745)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- TOC entry 222 (class 1259 OID 16744)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 219 (class 1259 OID 16731)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- TOC entry 218 (class 1259 OID 16730)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 16751)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


--
-- TOC entry 227 (class 1259 OID 16759)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


--
-- TOC entry 226 (class 1259 OID 16758)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 16750)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 16765)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- TOC entry 228 (class 1259 OID 16764)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 246 (class 1259 OID 32848)
-- Name: defender_accessattempt; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.defender_accessattempt (
    id integer NOT NULL,
    user_agent character varying(255) NOT NULL,
    ip_address inet,
    username character varying(255),
    http_accept character varying(1025) NOT NULL,
    path_info character varying(255) NOT NULL,
    attempt_time timestamp with time zone NOT NULL,
    login_valid boolean NOT NULL
);


--
-- TOC entry 245 (class 1259 OID 32847)
-- Name: defender_accessattempt_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.defender_accessattempt ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.defender_accessattempt_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 16823)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- TOC entry 230 (class 1259 OID 16822)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 217 (class 1259 OID 16723)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- TOC entry 216 (class 1259 OID 16722)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 215 (class 1259 OID 16715)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- TOC entry 214 (class 1259 OID 16714)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 16851)
-- Name: django_session; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);



--
-- TOC entry 238 (class 1259 OID 24591)
-- Name: main_answermodel; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.main_answermodel (
    id bigint NOT NULL,
    info character varying(300) NOT NULL,
    correct_ans boolean NOT NULL,
    question_id bigint NOT NULL
);


--
-- TOC entry 237 (class 1259 OID 24590)
-- Name: main_answermodel_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.main_answermodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_answermodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 236 (class 1259 OID 24585)
-- Name: main_questionmodel; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.main_questionmodel (
    id bigint NOT NULL,
    info character varying(300) NOT NULL,
    quiz_id bigint NOT NULL,
    hint character varying(300)
);


--
-- TOC entry 235 (class 1259 OID 24584)
-- Name: main_questionmodel_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.main_questionmodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_questionmodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 242 (class 1259 OID 32807)
-- Name: main_quizcomments; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.main_quizcomments (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    body character varying(500),
    date timestamp with time zone NOT NULL,
    quiz_id bigint NOT NULL
);


--
-- TOC entry 241 (class 1259 OID 32806)
-- Name: main_quizcomments_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.main_quizcomments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_quizcomments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 234 (class 1259 OID 24577)
-- Name: main_quizmodel; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.main_quizmodel (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    descriptor character varying(500) NOT NULL,
    timelimit integer,
    questions integer,
    author_id integer NOT NULL
);


--
-- TOC entry 233 (class 1259 OID 24576)
-- Name: main_quizmodel_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.main_quizmodel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_quizmodel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 244 (class 1259 OID 32828)
-- Name: main_quizmodel_likes; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.main_quizmodel_likes (
    id bigint NOT NULL,
    quizmodel_id bigint NOT NULL,
    user_id integer NOT NULL
);


--
-- TOC entry 243 (class 1259 OID 32827)
-- Name: main_quizmodel_likes_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.main_quizmodel_likes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_quizmodel_likes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 240 (class 1259 OID 24618)
-- Name: main_quizresults; Type: TABLE; Schema: public; Owner: skroskznik
--

CREATE TABLE public.main_quizresults (
    id bigint NOT NULL,
    score double precision NOT NULL,
    quiz_id bigint NOT NULL,
    user_id integer NOT NULL
);


--
-- TOC entry 239 (class 1259 OID 24617)
-- Name: main_quizresults_id_seq; Type: SEQUENCE; Schema: public; Owner: skroskznik
--

ALTER TABLE public.main_quizresults ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_quizresults_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 3266 (class 2606 OID 16849)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 3271 (class 2606 OID 16780)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 3274 (class 2606 OID 16749)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3268 (class 2606 OID 16741)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 3261 (class 2606 OID 16771)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 3263 (class 2606 OID 16735)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 3282 (class 2606 OID 16763)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 3285 (class 2606 OID 16795)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 3276 (class 2606 OID 16755)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 3288 (class 2606 OID 16769)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 3291 (class 2606 OID 16809)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 3279 (class 2606 OID 16844)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 3323 (class 2606 OID 32854)
-- Name: defender_accessattempt defender_accessattempt_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.defender_accessattempt
    ADD CONSTRAINT defender_accessattempt_pkey PRIMARY KEY (id);


--
-- TOC entry 3294 (class 2606 OID 16830)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 3256 (class 2606 OID 16729)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 3258 (class 2606 OID 16727)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 3254 (class 2606 OID 16721)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 3298 (class 2606 OID 16857)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 3307 (class 2606 OID 24595)
-- Name: main_answermodel main_answermodel_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_answermodel
    ADD CONSTRAINT main_answermodel_pkey PRIMARY KEY (id);


--
-- TOC entry 3304 (class 2606 OID 24589)
-- Name: main_questionmodel main_questionmodel_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_questionmodel
    ADD CONSTRAINT main_questionmodel_pkey PRIMARY KEY (id);


--
-- TOC entry 3314 (class 2606 OID 32813)
-- Name: main_quizcomments main_quizcomments_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizcomments
    ADD CONSTRAINT main_quizcomments_pkey PRIMARY KEY (id);


--
-- TOC entry 3317 (class 2606 OID 32832)
-- Name: main_quizmodel_likes main_quizmodel_likes_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizmodel_likes
    ADD CONSTRAINT main_quizmodel_likes_pkey PRIMARY KEY (id);


--
-- TOC entry 3320 (class 2606 OID 32834)
-- Name: main_quizmodel_likes main_quizmodel_likes_quizmodel_id_user_id_31a7af94_uniq; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizmodel_likes
    ADD CONSTRAINT main_quizmodel_likes_quizmodel_id_user_id_31a7af94_uniq UNIQUE (quizmodel_id, user_id);


--
-- TOC entry 3302 (class 2606 OID 24583)
-- Name: main_quizmodel main_quizmodel_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizmodel
    ADD CONSTRAINT main_quizmodel_pkey PRIMARY KEY (id);


--
-- TOC entry 3310 (class 2606 OID 24622)
-- Name: main_quizresults main_quizresults_pkey; Type: CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizresults
    ADD CONSTRAINT main_quizresults_pkey PRIMARY KEY (id);


--
-- TOC entry 3264 (class 1259 OID 16850)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 3269 (class 1259 OID 16791)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 3272 (class 1259 OID 16792)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 3259 (class 1259 OID 16777)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 3280 (class 1259 OID 16807)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 3283 (class 1259 OID 16806)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 3286 (class 1259 OID 16821)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 3289 (class 1259 OID 16820)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 3277 (class 1259 OID 16845)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 3292 (class 1259 OID 16841)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 3295 (class 1259 OID 16842)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 3296 (class 1259 OID 16859)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 3299 (class 1259 OID 16858)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 3308 (class 1259 OID 24613)
-- Name: main_answermodel_question_id_ef7d043d; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX main_answermodel_question_id_ef7d043d ON public.main_answermodel USING btree (question_id);


--
-- TOC entry 3305 (class 1259 OID 24607)
-- Name: main_questionmodel_quiz_id_08fe8bf6; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX main_questionmodel_quiz_id_08fe8bf6 ON public.main_questionmodel USING btree (quiz_id);


--
-- TOC entry 3315 (class 1259 OID 32819)
-- Name: main_quizcomments_quiz_id_2f5e20b0; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX main_quizcomments_quiz_id_2f5e20b0 ON public.main_quizcomments USING btree (quiz_id);


--
-- TOC entry 3300 (class 1259 OID 24601)
-- Name: main_quizmodel_author_id_b6554f74; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX main_quizmodel_author_id_b6554f74 ON public.main_quizmodel USING btree (author_id);


--
-- TOC entry 3318 (class 1259 OID 32845)
-- Name: main_quizmodel_likes_quizmodel_id_39a9877b; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX main_quizmodel_likes_quizmodel_id_39a9877b ON public.main_quizmodel_likes USING btree (quizmodel_id);


--
-- TOC entry 3321 (class 1259 OID 32846)
-- Name: main_quizmodel_likes_user_id_eb3b109e; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX main_quizmodel_likes_user_id_eb3b109e ON public.main_quizmodel_likes USING btree (user_id);


--
-- TOC entry 3311 (class 1259 OID 24633)
-- Name: main_quizresults_quiz_id_937dee6b; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX main_quizresults_quiz_id_937dee6b ON public.main_quizresults USING btree (quiz_id);


--
-- TOC entry 3312 (class 1259 OID 24634)
-- Name: main_quizresults_user_id_65596cf6; Type: INDEX; Schema: public; Owner: skroskznik
--

CREATE INDEX main_quizresults_user_id_65596cf6 ON public.main_quizresults USING btree (user_id);


--
-- TOC entry 3325 (class 2606 OID 16786)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3326 (class 2606 OID 16781)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3324 (class 2606 OID 16772)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3327 (class 2606 OID 16801)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3328 (class 2606 OID 16796)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3329 (class 2606 OID 16815)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3330 (class 2606 OID 16810)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3331 (class 2606 OID 16831)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3332 (class 2606 OID 16836)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3335 (class 2606 OID 24608)
-- Name: main_answermodel main_answermodel_question_id_ef7d043d_fk_main_questionmodel_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_answermodel
    ADD CONSTRAINT main_answermodel_question_id_ef7d043d_fk_main_questionmodel_id FOREIGN KEY (question_id) REFERENCES public.main_questionmodel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3334 (class 2606 OID 24602)
-- Name: main_questionmodel main_questionmodel_quiz_id_08fe8bf6_fk_main_quizmodel_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_questionmodel
    ADD CONSTRAINT main_questionmodel_quiz_id_08fe8bf6_fk_main_quizmodel_id FOREIGN KEY (quiz_id) REFERENCES public.main_quizmodel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3338 (class 2606 OID 32814)
-- Name: main_quizcomments main_quizcomments_quiz_id_2f5e20b0_fk_main_quizmodel_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizcomments
    ADD CONSTRAINT main_quizcomments_quiz_id_2f5e20b0_fk_main_quizmodel_id FOREIGN KEY (quiz_id) REFERENCES public.main_quizmodel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3333 (class 2606 OID 24596)
-- Name: main_quizmodel main_quizmodel_author_id_b6554f74_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizmodel
    ADD CONSTRAINT main_quizmodel_author_id_b6554f74_fk_auth_user_id FOREIGN KEY (author_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3339 (class 2606 OID 32835)
-- Name: main_quizmodel_likes main_quizmodel_likes_quizmodel_id_39a9877b_fk_main_quizmodel_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizmodel_likes
    ADD CONSTRAINT main_quizmodel_likes_quizmodel_id_39a9877b_fk_main_quizmodel_id FOREIGN KEY (quizmodel_id) REFERENCES public.main_quizmodel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3340 (class 2606 OID 32840)
-- Name: main_quizmodel_likes main_quizmodel_likes_user_id_eb3b109e_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizmodel_likes
    ADD CONSTRAINT main_quizmodel_likes_user_id_eb3b109e_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3336 (class 2606 OID 24623)
-- Name: main_quizresults main_quizresults_quiz_id_937dee6b_fk_main_quizmodel_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizresults
    ADD CONSTRAINT main_quizresults_quiz_id_937dee6b_fk_main_quizmodel_id FOREIGN KEY (quiz_id) REFERENCES public.main_quizmodel(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 3337 (class 2606 OID 24628)
-- Name: main_quizresults main_quizresults_user_id_65596cf6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: skroskznik
--

ALTER TABLE ONLY public.main_quizresults
    ADD CONSTRAINT main_quizresults_user_id_65596cf6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


-- Completed on 2024-07-18 08:09:30

--
-- PostgreSQL database dump complete
--

