# Generated by Django 4.2.1 on 2023-07-15 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_quizmodel_hints_questionmodel_hint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='descriptor',
            field=models.CharField(help_text='Quiz Description', max_length=500),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='QuizComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quizmodel')),
            ],
        ),
    ]
