# Generated by Django 4.2.1 on 2023-07-15 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_quizmodel_descriptor_alter_quizmodel_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcomments',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='main.quizmodel'),
        ),
    ]
