# Generated by Django 4.2.1 on 2023-07-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_questionmodel_hint_alter_questionmodel_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='hint',
            field=models.CharField(help_text='Provide Hint For The Question', max_length=300, null=True),
        ),
    ]
