# Generated by Django 4.2.1 on 2023-07-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_quizcomments_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcomments',
            name='body',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
