# Generated by Django 4.2.1 on 2023-07-22 08:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_alter_quizmodel_name_alter_quizmodel_questions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizmodel',
            name='likes',
            field=models.ManyToManyField(related_name='quizblock', to=settings.AUTH_USER_MODEL),
        ),
    ]
