# Generated by Django 4.2.1 on 2023-07-22 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_quizmodel_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='info',
            field=models.CharField(help_text='Place An Answer Here', max_length=300),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='hint',
            field=models.CharField(help_text='Provide An Optional Hint For The Question', max_length=300, null=True),
        ),
    ]
