# Generated by Django 4.2.1 on 2023-07-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_answermodel_info_alter_questionmodel_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='info',
            field=models.CharField(max_length=300),
        ),
    ]
