# Generated by Django 4.2.1 on 2023-07-15 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_quizcomments_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionmodel',
            name='hint',
            field=models.CharField(help_text='Provide Hint For The Question', max_length=300),
        ),
        migrations.AlterField(
            model_name='questionmodel',
            name='info',
            field=models.CharField(help_text='What Is The Question?', max_length=300),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='timelimit',
            field=models.IntegerField(default=1, help_text='Quiz Duration in sec', null=True),
        ),
    ]
