# Generated by Django 4.2.1 on 2023-07-16 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_questionmodel_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizcomments',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
