# Generated by Django 4.2.1 on 2023-07-21 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_quizcomments_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizmodel',
            name='name',
            field=models.CharField(help_text='Quiz Name (50 Character Limit)', max_length=50),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='questions',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='quizmodel',
            name='timelimit',
            field=models.IntegerField(default=1, help_text='Quiz Duration in seconds', null=True),
        ),
    ]
