# Generated by Django 4.2.1 on 2023-07-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_answermodel_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answermodel',
            name='info',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
